---
- hosts: all
  pre_tasks:
    - name: gather ec2_metadata
      ec2_metadata_facts:
  roles:
    - s2ansible.yumrepo_common
    - s2ansible.yumrepo_epel
    - s2ansible.yumrepo_remi
    - role: s2ansible.yumrepo_zabbix
      when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7") or ( ansible_distribution == "Amazon")
    - role: s2ansible.yumrepo_zabbix30
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8" 
    - cloud3rsio.common_packages
    - cloud3rsio.update_all_packages
    - role: cloud3rsio.hostname
      hostname: example.com
    - cloud3rsio.iptables/disable
    - cloud3rsio.journald
    - cloud3rsio.kernel_params
    - cloud3rsio.logrotate_rules
    - role: s2ansible.admin_user
      name: admin-xxxx
      password: Passw0rd
      homedir: /home/admin-xxxx
      generate_ssh_key: yes
      ssh_key_passphrase: Passphrase
      additional_ssh_keys: []
    - s2ansible.selinux/disabled
    - role: cloud3rsio.swapfile
      swapfile_size: 1024
    - cloud3rsio.time
    - role: s2ansible.sshd
      sshd_port: 22
      sshd_user: user1 user2
    - s2ansible.postfix
    - role: s2ansible.rootpasswd
      root_password: Passw0rd
    - role: s2ansible.adminpasswd
      admin_password: Passw0rd
    - role: s2ansible.deluser
      delete_user: deluser
    - role: s2ansible.zabbix_agent
      zabbix_agent_UserParameters:
        - postfix.queuen,mailq | grep "^[0-9A-F]" | wc -l
        - redis.status[*],redis-cli info | grep -w "$1" | awk -F':' '{print $$2}'
        - redis.ping,redis-cli ping 2>/dev/null | grep -w 'PONG' | wc -l
      zabbix_agent_mysql:
        zabbix_mysql_user: root
        zabbix_mysql_password: Passw0rd
        zabbix_mysql_host: 127.0.0.1
    - role: s2ansible.zabbix_host
      zabbix_server_url: https://example.com
      zabbix_login_user: zabbix_login_user
      zabbix_login_password: password
      zabbix_host_name: hostname
      zabbix_host_groups: hostgroup
      zabbix_templates: templates
      public_ip: xxx.xxx.xxx.xxx
